# Generated by Django 2.2.3 on 2019-07-30 09:18

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
