# Generated by Django 2.2.3 on 2019-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiSystem', '0002_auto_20190730_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='preview',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(max_length=160),
        ),
    ]
